baseURL = 'https://mayaflux.org/'
languageCode = 'en-us'
title = 'MayaFlux'
theme = 'mayaflux-minimal'

[params]
description = "Digital-First Multimedia Computation Framework"

[params.homeInfoParams]
Title = "MayaFlux"
Content = "Revolutionary C++20 multimedia DSP framework - digital-first paradigms for audio, visual, and control data"

[[menu.main]]
name = "Download"
url = "/download/"
weight = 1

[[menu.main]]
name = "Personas"
url = "/personas/"
weight = 2

[[menu.main]]
name = "Onboarding"
url = "/onboarding/"
weight = 3

[[menu.main]]
name = "Tutorials"
identifier = "tutorials"
url = "/tutorials/"
weight = 4

[[menu.main]]
name = "Sculpting Data"
parent = "tutorials"
url = "/tutorials/sculpting-data/"
weight = 3

[[menu.main]]
name = "Workshops"
parent = "tutorials"
url = "/tutorials/workshops/"
weight = 2

[[menu.main]]
name = "Docs"
url = "https://mayaflux.github.io/MayaFlux/"
weight = 5

[[menu.main]]
name = "Releases"
identifier = "releases"
url = "/releases/"
weight = 6

[[menu.main]]
name = "News"
identifier = "news"
parent = "releases"
weight = 1

[[menu.main]]
name = "Stable Releases"
identifier = "stable"
parent = "releases"
weight = 2

[[menu.main]]
name = "Patch Releases"
identifier = "patch"
parent = "releases"
weight = 3

[[menu.main]]
name = "The Shape of Material"
parent = "news"
url = "/releases/news/the_shape_of_material/"
weight = 3

[[menu.main]]
name = "0.3.0"
parent = "stable"
url = "/releases/release/030/"
weight = 1

[[menu.main]]
name = "0.2.0"
parent = "stable"
url = "/releases/release/020/"
weight = 2

[[menu.main]]
name = "0.1.0"
parent = "stable"
url = "/releases/release/010/"
weight = 3

[[menu.main]]
name = "0.2"
parent = "patch"
url = "/releases/patch/02/"
weight = 1

[[menu.main]]
name = "0.1"
parent = "patch"
url = "/releases/patch/01/"
weight = 2

[[menu.main]]
name = "Posters"
url = "/posters/"
weight = 7

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = "github"

[markup.highlight]
noClasses = false

[markup.tableOfContents]
startLevel = 2
endLevel = 3
